chore(nvmf): drop supporting nvmi-cli < 2.5
The code to check the `nvme` command to support `--nbft` does not work
with busybox:

```sh
$ /usr/sbin/nvme connect-all --help 2>&1 | busybox sed -n '/[[:space:]]--nbft[[:space:]]/q1;$q0'
sed: unsupported command ;
```

Remove support for nvmi-cli < 2.5 because all containers have a recent
enough version (except for opensuse where `nvme` is not installed):

```
$ containers=(alpine:busybox-edge alpine:edge arch:latest azurelinux:latest centos:latest debian:latest debian:sid fedora:latest fedora:rawhide gentoo:amd64-openrc gentoo:latest opensuse:latest ubuntu:devel ubuntu:rolling void:latest)
$ for container in "${containers[@]}"; do podman run -it --rm "ghcr.io/dracut-ng/$container" /usr/sbin/nvme connect-all --help | grep -q -- --nbft || echo "$container"; done
Error: runc: runc create failed: unable to start container process: error during container init: exec: "/usr/sbin/nvme": stat /usr/sbin/nvme: no such file or directory: OCI runtime attempted to invoke a command that was not found
opensuse:latest
```